### ISSUE TITLE
problems with source code in visual studio.

### ISSUE THREAD

**Issue by Arwwarrr** [TadasBaltrusaitis/OpenFace#659]
I wanted to run the source code from GitHub, I used this repository: 
https://github.com/TadasBaltrusaitis/OpenFace/tree/feature/VS2017_changes)
I use the latest visual studio. The entire code can be compiled without any problems, but when I try to run, an exception is shown.

for better clarity in [pastebin ](https://pastebin.com/Tp4NkJ7t)= [https://pastebin.com/Tp4NkJ7t](https://pastebin.com/Tp4NkJ7t)

`System.Windows.Markup.XamlParseException
  HResult=0x80131501
  Zpráva=Vyvolání konstruktoru pro typ OpenFaceDemo.MainWindow, který odpovídá zadaným omezením vazby, vyvolalo výjimku.
  Zdroj=PresentationFramework
  StackTrace:
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at OpenFaceDemo.App.Main()`

Vnitřní výjimka 1:
FileNotFoundException: Nelze načíst soubor nebo sestavení CppInerop.dll nebo jeden z jejich závislých prvků. Uvedený modul nebyl nalezen.
`
[it contains also the main language of the computer, Czech]

Google translator: 

> Message  = Invoking the constructor for the OpenFaceDemo.MainWindow type that matches the specified binding constraint caused an exception.

+

> FileNotFoundException: Unable to load CppInerop.dll file or assembly or one of their dependent elements. This module was not found.

**Comment by TadasBaltrusaitis** [comment]
Are you sure CppInterop project compiled succesfully? It seems like the dll was not built or not placed in the right location.

**Comment by raghavendraLhci** [comment]
Hi @TadasBaltrusaitis ..

Thanks for your amazing project and great support on github.

I am able to compile the projects; FaceLandMarkImg, Vid and MultiVid.

Continuing the above discussion, when i tried to compile headposelive project or openfacedemo; 
the following error pops up


![image](https://user-images.githubusercontent.com/57899536/70616236-f6569280-1c33-11ea-9dd8-7799d241c37e.png)


I tried to compile the CPPInterop project and i got the above errors.

Any suggestions for the successful compilation?

Thanks in advance.

**Comment by TadasBaltrusaitis** [comment]
The issue might be the order of compilations, for some reason I see this message sometimes as well. You need to make sure you build the CppInterop project first, before building the C# ones.
